### ISSUE TITLE
#Help

### ISSUE THREAD

**Issue by helll7** [abhibagul/Melesa-Blogger-Template#1]
Hope You Doing well,

I just love your melesa template, can you please guide me or provide customization setting or read me in brief about how to setup template and how customize it in decent manner?

**Comment by abhibagul** [comment]
@helll7 Follow general installation procedures.

**Comment by abhibagul** [comment]
Hello,
Sorry for the late reply. To install the template following are the codes in brief. If possible try to convert it into the documentation. which can be added to the git.

1) Header Menu Style
regular, full-logo, compact, center-full, modern

2) Post Layout Styles
default  , big-post, grid-post,  

3) Featured Wid Styles
&lt;object id="demo-feat" class="melesa_widget" data-label="travel" data-type="grid-3">&lt;/object>

Change it to grid-1,grid-2,grid-3

4) Page Navigation Style
number , infinite, arrow

 
Regards,
Blossom Themes Team
